[build-system]
requires = ["hatchling>=1.20"]
build-backend = "hatchling.build"

[project]
name = "pyrox-client"                       # pip name
version = "0.0.1"
description = "HYROX race data client – retrieve full race results via Python"
authors = [{ name = "Vlad Matei" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.2",
    "fastparquet>=2024.5.0",
    "fsspec>=2024.2.0",
    "s3fs>=2024.2.0",
    "requests>=2.31",
    "platformdirs>=4.2.0",
]

[project.optional-dependencies]
duckdb = ["duckdb>=1.0.0"]


# You’re using a src/ layout. This tells Hatch which package to build.
[tool.hatch.build.targets.wheel]
packages = ["src/pyrox"]

# Ensure sdist includes your source + docs
[tool.hatch.build.targets.sdist]
include = [
  "src/pyrox",
  "README.md",
  "pyproject.toml"
]
