name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    #Â run everything inside the uv image
    container:
      image: ghcr.io/astral-sh/uv:python3.12-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync dependencies with uv
        run: uv sync --all-extras

      - name: Run unit-tests
        run: uv run pytest -vv

      - name: Run integration tests
        run: uv run pytest -vv --only-integration

      - name: Build package
        run: uv build